version: "3.8"
services:
  admiralis-db:
    image: mongo
    restart: unless-stopped
    container_name: admiralis-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: rootdb
    volumes:
      - admiralis-db:/data
volumes:
  admiralis-db: